version: '3.7'

services:
    backend:
        build: ./backend
        container_name: ${BACKEND_CONTAINER_NAME}
        networks:
            - my-network
        depends_on:
            - database
        env_file: .env

    database:
        build: ./database
        container_name: ${DATABASE_CONTAINER_NAME}
        networks:
            - my-network
        volumes:
            - db-persitence:/var/lib/postgresql/data
        env_file: .env

    httpd:
        build: ./http
        container_name: ${PROXY_CONTAINER_NAME}
        ports:
            - "80:80"
        networks:
            - my-network
        depends_on:
            - backend
        env_file: .env

networks:
    my-network: {}

volumes:
    db-persitence: {}
