---
- name: Create the proxy container
  community.docker.docker_container:
    name: "{{ proxy.container_name }}"
    image: e10e3/ops-proxy
    pull: true
    networks:
      - name: app_network
    ports:
      - "80:80"
    env:
      BACKEND_CONTAINER_NAME: "{{ backend.container_name }}"
      FRONTEND_CONTAINER_NAME: "{{ frontend.container_name }}"
