---
- name: Create the database container
  community.docker.docker_container:
    name: "{{ database.container_name }}"
    image: e10e3/ops-database
    pull: true
    volumes:
      - db_storage:/var/lib/postgresql/data
    networks:
      - name: app_network
    env:
      POSTGRES_DB: "{{ database.postgres_name }}"
      POSTGRES_USER: "{{ database.postgres_username }}"
      POSTGRES_PASSWORD: "{{ database.postgres_password }}"
