---
- hosts: all
  gather_facts: false
  become: true
  vars_files:
    - env.yaml

  tasks:
    - name: Test connection
      ping:

  roles:
    - install_docker
    - create_network
    - create_volume
    - launch_database
    - launch_app
    - launch_frontend
    - launch_proxy
